wayland: Support LWQt
Instead of LXQt, launch LWQt.

diff --git a/startlxqt.in b/startlxqt.in
--- a/startlxqt.in
+++ b/startlxqt.in
@@ -43,26 +43,27 @@ else
 fi
 mkdir -p "$XDG_DESKTOP_DIR"
 
-# Clean up after GDM (GDM sets the number of desktops to one)
-xprop -root -remove _NET_NUMBER_OF_DESKTOPS -remove _NET_DESKTOP_NAMES -remove _NET_CURRENT_DESKTOP 2> /dev/null
-
 # Launch DBus if needed
 if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
     if [ -z "$XDG_RUNTIME_DIR" ] || ! [ -S "$XDG_RUNTIME_DIR/bus" ] || ! [ -O "$XDG_RUNTIME_DIR/bus" ]; then
-        eval "$(dbus-launch --sh-syntax --exit-with-session)" || echo "startlxqt: error executing dbus-launch" >&2
+        eval "$(dbus-launch --sh-syntax --exit-with-session)" || echo "startlwqt: error executing dbus-launch" >&2
     fi
 fi
 
+export GTK_USE_PORTAL=1
+export GDK_DEBUG=portals
+
 # Qt4 platform plugin
-export QT_PLATFORM_PLUGIN=lxqt
+export QT_PLATFORM_PLUGIN=gtk3
 
 # Qt5 platform plugin
-export QT_QPA_PLATFORMTHEME=lxqt
+export QT_QPA_PLATFORMTHEME=gtk3
 
 # use lxqt-applications.menu for main app menu
 export XDG_MENU_PREFIX="lxqt-"
 
-export XDG_CURRENT_DESKTOP="LXQt"
+export XDG_CURRENT_DESKTOP="LWQt"
+export XDG_SESSION_TYPE="wayland"
 
-# Start the LXQt session
-exec lxqt-session
+# Start the LWQt session
+exec mutter $@ -- lwqt-session
